import React,{useMemo,useState}from"react";
import{LayoutDashboard,Inbox,BookOpen,MessageSquareText,Settings,Search,Plus,Trash2,Pencil,Copy,Star,Globe2,Upload,Save,ChevronRight,Sparkles,Check,Languages,PanelLeftClose,PanelLeftOpen,FileText,SlidersHorizontal}from"lucide-react";

const seedUtilities=[
{id:1,cat:"Opening",lang:"NL",text:"Bedankt voor uw bericht. We helpen u graag verder met uw vraag."},
{id:2,cat:"Opening",lang:"EN",text:"Thank you for your message. We are happy to help you with your request."},
{id:3,cat:"Troubleshooting",lang:"NL",text:"Kunt u onderstaande stappen uitvoeren en ons laten weten wat het resultaat is?"},
{id:4,cat:"Closing",lang:"NL",text:"Als u nog vragen heeft, mag u ons altijd opnieuw contacteren."},
{id:5,cat:"Closing",lang:"EN",text:"If you have any further questions, please feel free to contact us again."}
];

const seedCases=[
{id:101,title:"VPN connection drops",customer:"Acme Belgium",status:"Open",updated:"Today",info:"Customer reports VPN disconnecting every 10–15 minutes. Started after laptop update. Remote access is available.",mail:""},
{id:102,title:"Account locked after MFA",customer:"Northwind",status:"Waiting",updated:"Yesterday",info:"User receives MFA challenge but account remains locked after successful verification.",mail:""}
];

function App(){
 const[page,setPage]=useState("Dashboard"),[collapsed,setCollapsed]=useState(false),[query,setQuery]=useState(""),[language,setLanguage]=useState("NL");
 const[utilities,setUtilities]=useState(seedUtilities),[utilCat,setUtilCat]=useState("All"),[editingUtil,setEditingUtil]=useState(null);
 const[cases,setCases]=useState(seedCases),[activeCase,setActiveCase]=useState(seedCases[0]),[caseInfo,setCaseInfo]=useState(seedCases[0].info),[mail,setMail]=useState(seedCases[0].mail);
 const[cats,setCats]=useState(["Opening","Troubleshooting","Closing","Escalation","Other"]);
 const[guideFiles,setGuideFiles]=useState([]);
 const[selectedTool,setSelectedTool]=useState("Language");
 const filteredUtils=useMemo(()=>utilities.filter(u=>(utilCat==="All"||u.cat===utilCat)&&(!query||u.text.toLowerCase().includes(query.toLowerCase()))),[utilities,utilCat,query]);
 const nav=[["Dashboard",LayoutDashboard],["Cases",Inbox],["Utilities",MessageSquareText],["Guides",BookOpen],["Templates",FileText],["Settings",Settings]];
 const openCase=c=>{setActiveCase(c);setCaseInfo(c.info);setMail(c.mail||"");setPage("Cases")};
 const saveCase=()=>{setCases(cs=>cs.map(c=>c.id===activeCase.id?{...c,info:caseInfo,mail}:c));setActiveCase(c=>({...c,info:caseInfo,mail}))};
 const insert=(text)=>setMail(m=>(m?m+"\n\n":"")+text);
 const addUtility=()=>{const u={id:Date.now(),cat:cats[0],lang:language,text:"New standard sentence..."};setUtilities(x=>[u,...x]);setEditingUtil(u)};
 const saveUtility=u=>{setUtilities(x=>x.map(v=>v.id===u.id?u:v));setEditingUtil(null)};
 return <div className="app">
  <aside className={"sidebar "+(collapsed?"collapsed":"")}>
   <div className="brand"><div className="brandmark">TS</div>{!collapsed&&<div><b>Support</b><span>Workbench</span></div>}</div>
   <button className="collapse" onClick={()=>setCollapsed(!collapsed)}>{collapsed?<PanelLeftOpen size={18}/>:<PanelLeftClose size={18}/>}</button>
   <div className="nav">{nav.map(([name,Icon])=><button className={page===name?"active":""} onClick={()=>setPage(name)} key={name}><Icon size={18}/>{!collapsed&&<span>{name}</span>}{name==="Cases"&&!collapsed&&<em>{cases.length}</em>}</button>)}</div>
   {!collapsed&&<div className="side-bottom"><div className="status-dot"></div><div><b>Workspace ready</b><small>Local data mode</small></div></div>}
  </aside>
  <main className="main">
   <header className="topbar"><div className="crumb">{page}<ChevronRight size={15}/><span>{page==="Cases"?(activeCase?.title||"Case"):page==="Utilities"?"Sentence library":"Workspace"}</span></div><div className="top-actions"><div className="global-search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search workspace..."/></div><select value={language} onChange={e=>setLanguage(e.target.value)}><option>NL</option><option>EN</option></select><div className="avatar">MV</div></div></header>
   <section className="content">
    {page==="Dashboard"&&<Dashboard cases={cases} utilities={utilities} openCase={openCase} setPage={setPage}/>}
    {page==="Utilities"&&<Utilities utilities={utilities} cats={cats} setCats={setCats} utilCat={utilCat} setUtilCat={setUtilCat} filteredUtils={filteredUtils} addUtility={addUtility} editingUtil={editingUtil} setEditingUtil={setEditingUtil} saveUtility={saveUtility} setUtilities={setUtilities} insert={insert}/>}
    {page==="Cases"&&<Cases cases={cases} activeCase={activeCase} setActiveCase={openCase} caseInfo={caseInfo} setCaseInfo={setCaseInfo} mail={mail} setMail={setMail} saveCase={saveCase} insert={insert}/>}
    {page==="Guides"&&<Guides files={guideFiles} setFiles={setGuideFiles}/>}
    {page==="Templates"&&<Templates language={language} insert={insert}/>}
    {page==="Settings"&&<SettingsPage language={language} setLanguage={setLanguage}/>}
   </section>
  </main>
 </div>
}

function Dashboard({cases,utilities,openCase,setPage}){return <><div className="hero"><div><span className="eyebrow">TECHNICAL SUPPORT</span><h1>Good evening, Maikel.</h1><p>Your support workspace is ready. Manage cases, reusable language and guides from one place.</p></div><button className="primary" onClick={()=>setPage("Cases")}><Plus size={17}/> New case</button></div><div className="stats"><Stat icon={Inbox} label="Active cases" value={cases.length}/><Stat icon={MessageSquareText} label="Utilities" value={utilities.length}/><Stat icon={BookOpen} label="Guides" value="0"/><Stat icon={Sparkles} label="AI status" value="Ready"/></div><div className="grid2"><div className="card"><div className="cardhead"><div><b>Recent cases</b><span>Continue where you left off</span></div><button className="ghost" onClick={()=>setPage("Cases")}>View all</button></div>{cases.map(c=><button className="case-row" key={c.id} onClick={()=>openCase(c)}><div className="case-icon"><Inbox size={17}/></div><div><b>{c.title}</b><small>{c.customer} · {c.updated}</small></div><span className={"pill "+c.status.toLowerCase()}>{c.status}</span><ChevronRight size={16}/></button>)}</div><div className="card"><div className="cardhead"><div><b>Quick actions</b><span>Common support workflows</span></div></div><div className="quick"><button onClick={()=>setPage("Utilities")}><MessageSquareText/><b>Sentence library</b><span>Insert approved wording</span></button><button onClick={()=>setPage("Guides")}><BookOpen/><b>Import guide</b><span>Add PDF, DOCX or text knowledge</span></button><button onClick={()=>setPage("Templates")}><FileText/><b>Mail templates</b><span>Build reusable replies</span></button></div></div></div></>}

function Stat({icon:Icon,label,value}){return <div className="stat"><Icon size={19}/><span>{label}</span><b>{value}</b></div>}

function Utilities({utilities,cats,setCats,utilCat,setUtilCat,filteredUtils,addUtility,editingUtil,setEditingUtil,saveUtility,setUtilities,insert}){const[catDraft,setCatDraft]=useState("");return <><div className="page-title"><div><span className="eyebrow">LIBRARY</span><h1>Utilities</h1><p>Maintain standard sentences and reusable support wording.</p></div><button className="primary" onClick={addUtility}><Plus size={17}/> Add sentence</button></div><div className="utility-layout"><div className="card category-card"><div className="cardhead"><div><b>Categories</b><span>Structure your library</span></div></div><button className={utilCat==="All"?"cat active":"cat"} onClick={()=>setUtilCat("All")}>All <span>{utilities.length}</span></button>{cats.map(c=><button className={utilCat===c?"cat active":"cat"} key={c} onClick={()=>setUtilCat(c)}>{c}<span>{utilities.filter(x=>x.cat===c).length}</span></button>)}<div className="add-cat"><input value={catDraft} onChange={e=>setCatDraft(e.target.value)} placeholder="New category"/><button onClick={()=>{if(catDraft.trim()){setCats(x=>[...x,catDraft.trim()]);setCatDraft("")}}}><Plus size={15}/></button></div></div><div className="card"><div className="toolbar"><div className="language-tabs"><button className="selected">All</button><button>NL</button><button>EN</button></div><span className="muted">{filteredUtils.length} sentences</span></div><div className="sentence-list">{filteredUtils.map(u=><div className="sentence" key={u.id}><div className="sentence-main"><div className="sentence-meta"><span>{u.cat}</span><span>{u.lang}</span></div>{editingUtil?.id===u.id?<textarea value={editingUtil.text} onChange={e=>setEditingUtil({...editingUtil,text:e.target.value})}/>:<p>{u.text}</p>}</div><div className="row-actions">{editingUtil?.id===u.id?<button className="icon-btn save" onClick={()=>saveUtility(editingUtil)}><Check size={16}/></button>:<><button className="icon-btn" title="Insert" onClick={()=>insert(u.text)}><Copy size={16}/></button><button className="icon-btn" onClick={()=>setEditingUtil(u)}><Pencil size={16}/></button><button className="icon-btn danger" onClick={()=>setUtilities(x=>x.filter(v=>v.id!==u.id))}><Trash2 size={16}/></button></>}</div></div>)}</div></div></div></>}

function Cases({cases,activeCase,setActiveCase,caseInfo,setCaseInfo,mail,setMail,saveCase,insert}){return <div className="cases-page"><div className="page-title compact"><div><span className="eyebrow">CASE MANAGEMENT</span><h1>Cases</h1></div><button className="primary"><Plus size={17}/> New case</button></div><div className="case-workspace"><aside className="case-list card">{cases.map(c=><button className={activeCase?.id===c.id?"case-select active":"case-select"} onClick={()=>setActiveCase(c)} key={c.id}><div><b>{c.title}</b><small>{c.customer}</small></div><span className={"pill "+c.status.toLowerCase()}>{c.status}</span></button>)}</aside><div className="editor-grid"><EditorPanel title="Case information" subtitle="Paste, structure and analyse the incoming case" toolbar={<button className="ai-btn"><Sparkles size={15}/> Analyse with AI</button>}><textarea className="big-editor" value={caseInfo} onChange={e=>setCaseInfo(e.target.value)} placeholder="Paste the customer issue, logs, notes, device information or troubleshooting history here..."/><div className="editor-footer"><span><Check size={14}/> Autosave ready</span><span>Plain text</span></div></EditorPanel><EditorPanel title="Customer mail" subtitle="Write the final response in a Word-like editor" toolbar={<div className="toolbar-mini"><button onClick={()=>insert("Bedankt voor uw bericht. ")}>Insert utility</button><button><Languages size={14}/> {mail.includes("Dear")?"EN":"NL"}</button></div>}><div className="formatbar"><button><b>B</b></button><button><i>I</i></button><button><u>U</u></button><span></span><button>• List</button><button>↔</button></div><textarea className="mail-editor" value={mail} onChange={e=>setMail(e.target.value)} placeholder="Start writing the customer response..."/><div className="editor-footer"><span><Languages size={14}/> Language detection ready</span><span>{mail.trim().split(/\s+/).filter(Boolean).length} words</span></div></EditorPanel></div></div><div className="bottom-bar"><div><b>{activeCase?.title}</b><span>Changes are kept in this workspace.</span></div><button className="secondary">Preview</button><button className="primary" onClick={saveCase}><Save size={16}/> Save case</button></div></div>}

function EditorPanel({title,subtitle,toolbar,children}){return <div className="card editor-panel"><div className="editor-head"><div><b>{title}</b><span>{subtitle}</span></div>{toolbar}</div>{children}</div>}

function Guides({files,setFiles}){const onFiles=e=>setFiles([...files,...Array.from(e.target.files||[]).map(f=>({name:f.name,size:f.size,type:f.type}))]);return <><div className="page-title"><div><span className="eyebrow">KNOWLEDGE</span><h1>Guides</h1><p>Import support documentation and keep your knowledge base organised.</p></div><label className="primary upload"><Upload size={17}/> Import guides<input type="file" multiple accept=".pdf,.doc,.docx,.txt,.md,.html" onChange={onFiles}/></label></div><div className="card upload-zone"><BookOpen size={32}/><h3>Drop guides here</h3><p>PDF, DOCX, TXT, Markdown and HTML are supported by the workspace.</p><label className="secondary upload">Choose files<input type="file" multiple accept=".pdf,.doc,.docx,.txt,.md,.html" onChange={onFiles}/></label></div><div className="card"><div className="cardhead"><div><b>Imported guides</b><span>Ready for search and AI retrieval</span></div></div>{files.length?files.map((f,i)=><div className="file-row" key={i}><FileText size={18}/><div><b>{f.name}</b><small>{Math.ceil(f.size/1024)} KB</small></div><span>Imported</span></div>):<div className="empty">No guides imported yet.</div>}</div></>}

function Templates({language,insert}){const[templates,setTemplates]=useState([{id:1,name:"General response",cat:"General",body:language==="NL"?"Beste klant,\n\nBedankt voor uw bericht. We bekijken uw vraag en helpen u graag verder.\n\nMet vriendelijke groeten,\nTechnical Support":"Dear customer,\n\nThank you for your message. We will review your request and be happy to assist you.\n\nKind regards,\nTechnical Support"}]);const[active,setActive]=useState(templates[0]);return <><div className="page-title"><div><span className="eyebrow">REUSABLE COPY</span><h1>Templates</h1><p>Build full customer replies around your standard sentences.</p></div><button className="primary" onClick={()=>{const t={id:Date.now(),name:"New template",cat:"General",body:""};setTemplates(x=>[...x,t]);setActive(t)}}><Plus size={17}/> New template</button></div><div className="template-grid"><div className="card template-list">{templates.map(t=><button className={active.id===t.id?"template-item active":"template-item"} onClick={()=>setActive(t)} key={t.id}><FileText size={17}/><div><b>{t.name}</b><small>{t.cat}</small></div></button>)}</div><div className="card template-editor"><input className="title-input" value={active.name} onChange={e=>{const t={...active,name:e.target.value};setActive(t);setTemplates(x=>x.map(v=>v.id===t.id?t:v))}}/><div className="formatbar"><button><b>B</b></button><button><i>I</i></button><button><u>U</u></button></div><textarea value={active.body} onChange={e=>{const t={...active,body:e.target.value};setActive(t);setTemplates(x=>x.map(v=>v.id===t.id?t:v))}}/><div className="editor-footer"><span>Language: {language}</span><button className="secondary" onClick={()=>insert(active.body)}>Insert into mail</button></div></div></div></>}

function SettingsPage({language,setLanguage}){return <><div className="page-title"><div><span className="eyebrow">WORKSPACE</span><h1>Settings</h1><p>Configure the support workbench and future integrations.</p></div></div><div className="settings-grid"><div className="card setting-section"><div className="setting-title"><Globe2/><div><b>Language & writing</b><span>Default editor behaviour</span></div></div><label>Default language<select value={language} onChange={e=>setLanguage(e.target.value)}><option>NL</option><option>EN</option></select></label><label className="toggle"><input type="checkbox" defaultChecked/><span></span>Automatic spelling and grammar detection</label><label className="toggle"><input type="checkbox" defaultChecked/><span></span>Suggest standard sentences while writing</label></div><div className="card setting-section"><div className="setting-title"><Sparkles/><div><b>AI integrations</b><span>Connect your preferred assistant later</span></div></div><div className="integration"><div><b>Microsoft Copilot</b><small>Designed for Copilot / Copilot Studio integration through a secure backend.</small></div><span className="pill waiting">Not connected</span></div><div className="integration"><div><b>Local AI</b><small>Keep sensitive support data inside your own environment.</small></div><span className="pill waiting">Available</span></div></div><div className="card setting-section"><div className="setting-title"><SlidersHorizontal/><div><b>Workspace behaviour</b><span>Data and interface</span></div></div><label className="toggle"><input type="checkbox" defaultChecked/><span></span>Autosave case edits</label><label className="toggle"><input type="checkbox" defaultChecked/><span></span>Keep imported guides searchable</label><p className="notice">This first version stores workspace data locally in the browser. Add a backend/database when you are ready for multi-user persistence and secure AI integrations.</p></div></div></>}

export default App;